spring:
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

gcp:
  project-id: triprooty
  bucket: triprooty-uploads           # 만든 버킷명
  credentials:
    location: classpath:triprooty-3f47bb6a6f5a.json   # 방금 올린 JSON 경로
